### PR TITLE
Added functionality to handle Result in node compiler

### PR DESCRIPTION
**Pull request by lukewestby**
I really like the approach you're taking here and wanted to help out :smile:
Even if you'd rather not accept the changes I would love any feedback if you have time. Thanks!

- Added a record type to represent the `Result` from `prettyPrint` in node
- Added a helper function to make that conversion
- Updated node compiler to exit with code 1 if the `Result` is `Err`
- Updated example elm file to use `Css` correctly

### CODE REVIEW

**Comment by rtfeldman** [comment]
Hell yeah! This looks fantastic! :smile_cat: 

Sorry I took so long getting to this. I've merged the `mvp` branch into `master`, so if you don't mind making a new PR against `master`, I would love to accept this!

**Comment by lukewestby** [comment]
Neat! I'll gladly do that at some point today. Would it be cool if I submitted one or more additional PRs in the near future to help get a command-line tool working for this as well?

**Comment by rtfeldman** [comment]
Absolutely! :grinning:

**Comment by lukewestby** [comment]
Moved changes to master branch

**Pull request closed without merging**
