### PR TITLE
Add support for compiling many stylesheets

### PR DESCRIPTION
**Pull request by scottcorgan**
I'm open to rename the function, but I wasn't sure what the convention was for describing an _n_ number of arguments. Maybe it's something like `compileN`?

### CODE REVIEW

**Comment by rtfeldman** [comment]
Cool! I feel like we should just replace `compile` with this. Doesn't really seem like there's a need for both functions, and this one is more useful.

I'd avoid `foldr` though, so we don't make so many intermediate data structures - something like:

```elm
compile : List Preprocess.Stylesheet -> { warnings: List String, css: String }
compile styles =
    let
        results =
            List.map compile styles
    in
        { warnings = List.concatMap .warnings results
        , css = List.join "\n\n" (List.map .css results)
        }
```

**Comment by scottcorgan** [comment]
Fair enough. I didn't think that memory/extra data structures mattered as this isn't a feature with too much of a performance concern. I'll try some recursion though! Thanks!

**Comment by scottcorgan** [comment]
Amended to last commit

**Comment by rtfeldman** [comment]
Fantastic, thanks! I'm gonna merge this now, but unless it's urgently needed, I'd rather wait to publish until there's another breaking change (which actually I suspect `float` will be).

**Comment by scottcorgan** [comment]
Thanks! No rush, I'm just using a custom function until it gets merged.

**Pull request merged**
