### PR TITLE
Add `pointer-events` property

### PR DESCRIPTION
**Pull request by gurdiga**
## Summary

Another try to solve https://github.com/rtfeldman/elm-css/issues/247. (First was https://github.com/rtfeldman/elm-css/pull/276 which seems to be abandoned because the conversation stopped on Jun 11, 2017. 🤔)

This is my first totally-shot-in-the-dark PR, and I’m open to guidance. 🙃 Is this close to how the **Right Way®**? 🤓

 ### The `format` NPM script

The initial build for this PR failed because I had a different version of `elm-format` installed globally.  😑

To prevent this for other contributors, I’ve also added the `format` NPM script — now at least there is some hint about the formatting requirements. And, for that script to do the right thing I’ve also added `elm-format@0.7.0-exp` to the `devDependencies` so that we don’t depend on the individual contributor’s `elm-format` version. 😎

NOTE: This is totally movable to a separate PR if it’ll fit nicer that way. 🤓

### CODE REVIEW

**Comment by gurdiga** [comment]
@rtfeldman Ping! 🙃

Does this thing work? If there is anything to fix here, I’d be glad to. 🤓 Or if there is a [CONTRIBUTING.md](https://github.com/blog/1184-contributing-guidelines) somewhere that I can read about the further steps with this. 👷‍♂️

**Comment by rtfeldman** [comment]
Thanks for working on this!

Initial thoughts:

1. `fill` and `visible` should be overloaded to work with this, so `pointerEvents fill` and `pointerEvents visible` can work instead of `pointerEventsFill` and `pointerEventsVisible`
2. We need to support `pointerEvents all`
3. I'd like the `{-| -}` doc comments to be replaced with docs that link to `pointerEvents` so there's a direct trail people can use to figure out what it's intended to be used with.

**Comment by gurdiga** [comment]
@rtfeldman Replaced `pointerEventsVisible` with `pointerEvents visible` — changed the definition of `visible` to fit by following the example of `scroll`. If that doesn’t work well, I’m open to ideas and guidance. 🤓 

As for the `pointerEvents fill` and `pointerEvents all`, it’s my understanding that we can’t have `fill` and `all` **as values** because they already exist to designate **properties**. :neckbeard: So besides `pointerEventsFill` I have also added `pointerEventsAll`.

Added descriptions and links for the values, and also listed the new things in the Properties, Other values, and Misc `@docs` sections. 📜

Anything else? 🤓

**Comment by gurdiga** [comment]
@rtfeldman The `AppVeyor` part of build seems to have failed because of a failed download: 😶
```
Error: The following HTTP request failed.
<https://github.com/eeue56/elm-lazy-list/zipball/1.0.0/>
eeue56-elm-lazy-list-b3637ce/tests/elm-package.json: openBinaryFile: does not exist (No such file or directory)
```
Checked that URL and it seems to be working now, so I think this could have been a temporary issue. :neckbeard: 

Looked around its UI but couldn’t find a restart button, is it because I don’t have enough privileges? 🤔

**Comment by gurdiga** [comment]
@rtfeldman Ping again! 🙃

(Sorry fo the impatience! If there are other ways to progress with this other than poking at you, I’m open to any of them. 🤓)

**Comment by tolgap** [comment]
@gurdiga If you want to immediately use this, you could clone `elm-css` into your project like this:

```
/
  elm-package.json
  /src
    Main.elm
  /vendor
    /elm-css
```

and change the `source-directories` array inside `elm-package.json` to include `vendor/elm-css` as well. You can then use git checkout to switch to any feature branch you want 👍 . You could even add your own `elm-css` fork as a different `origin` to switch between your fork and master.

**Comment by rtfeldman** [comment]
Thanks @gurdiga!

I've merged this, but because it's a `MAJOR` change, I want to batch it with https://github.com/rtfeldman/elm-css/issues/375 - which is a ways off from being finished.

I appreciate your patience on this. ❤️

**Pull request merged**
